"""指标配置中心。

新增指标时，在 INDICATORS 中增加一条配置；抓取主程序无需改动。
数据源函数均由配置指定的数据提供方模块动态解析。
"""

INDICATORS = {
    "gold_copper_ratio": {
        "name": "金铜比",
        "description": "COMEX 黄金主连收盘价 / COMEX 铜主连收盘价",
        "chart_type": "line",
        "frequency": "daily",
        "history_years": 20,
        "unit": "倍",
        "output_file": "docs/data/gold_copper_ratio.json",
        "formula": "gold / copper",
        "source": "Yahoo Finance / COMEX futures",
        "series": {
            "gold": {
                "name": "COMEX 黄金",
                "provider": "yfinance",
                "function": "download",
                "retries": 3,
                "retry_delay_seconds": 10,
                "params": {
                    "tickers": "GC=F",
                    "period": "max",
                    "interval": "1d",
                    "auto_adjust": False,
                    "progress": False,
                },
                "date_column": "Date",
                "value_column": "Close",
                "unit": "美元/金衡盎司",
            },
            "copper": {
                "name": "COMEX 铜",
                "provider": "yfinance",
                "function": "download",
                "retries": 3,
                "retry_delay_seconds": 10,
                "params": {
                    "tickers": "HG=F",
                    "period": "max",
                    "interval": "1d",
                    "auto_adjust": False,
                    "progress": False,
                },
                "date_column": "Date",
                "value_column": "Close",
                "unit": "美元/磅",
            },
        },
    },
    "usd_jpy": {
        "name": "美元兑日元",
        "description": "美元兑日元（USD/JPY）日度收盘汇率",
        "chart_type": "line",
        "frequency": "daily",
        "history_years": 20,
        "unit": "日元/美元",
        "output_file": "docs/data/usd_jpy.json",
        "formula": "usd_jpy",
        "source": "Yahoo Finance",
        "series": {
            "usd_jpy": {
                "name": "美元兑日元",
                "provider": "yfinance",
                "function": "download",
                "retries": 3,
                "retry_delay_seconds": 10,
                "params": {
                    "tickers": "JPY=X",
                    "period": "max",
                    "interval": "1d",
                    "auto_adjust": False,
                    "progress": False,
                },
                "date_column": "Date",
                "value_column": "Close",
                "unit": "日元/美元",
            },
        },
    },
    "us_10y_yields": {
        "name": "美国10年期收益率",
        "description": "美国10年期国债收益率、10年期TIPS实际收益率及10年期盈亏平衡通胀率",
        "chart_type": "line",
        "frequency": "daily",
        "history_years": 5,
        "unit": "%",
        "output_file": "docs/data/us_10y_yields.json",
        "formula": "nominal_yield",
        "source": "FRED",
        "series": {
            "nominal_yield": {
                "name": "美国10年期国债收益率",
                "provider": "pandas_datareader.data",
                "function": "DataReader",
                "params": {
                    "name": "DGS10",
                    "data_source": "fred",
                    "start": "2000-01-01",
                },
                "date_column": "DATE",
                "value_column": "DGS10",
                "unit": "%",
            },
            "tips_yield": {
                "name": "10年期TIPS实际收益率",
                "provider": "pandas_datareader.data",
                "function": "DataReader",
                "params": {
                    "name": "DFII10",
                    "data_source": "fred",
                    "start": "2000-01-01",
                },
                "date_column": "DATE",
                "value_column": "DFII10",
                "unit": "%",
            },
            "breakeven_inflation": {
                "name": "10年期盈亏平衡通胀率",
                "provider": "pandas_datareader.data",
                "function": "DataReader",
                "params": {
                    "name": "T10YIE",
                    "data_source": "fred",
                    "start": "2000-01-01",
                },
                "date_column": "DATE",
                "value_column": "T10YIE",
                "unit": "%",
            },
        },
    },
}
